.staging_deploy_script: &staging_deploy_script
    - echo "Deploying image with tag $DOCKER_IMAGE_TAG -- https://hub.docker.com/r/jimber/wallet"
    - docker pull jimber/wallet:staging
    - docker rm -f 3bot_wallet; true
    - docker run -d -it --network=jimber_proxy_net --name 3bot_wallet jimber/wallet:$DOCKER_IMAGE_TAG
#caching modules
cache:
  paths:
    - node_modules/
    - .yarn

#steps gitlab will take
stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - builder
  script:
    - docker build -t wallet-test -f Dockerfile.test .
    - docker run --rm wallet-test

staging_build:
  stage: build
  dependencies: []
  variables:
    DOCKER_IMAGE_TAG: staging
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
  tags:
    - builder
  script:
    - cp public/staging.config.js public/config.js
    - docker build -t jimber/wallet:staging .
    - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
    - docker push jimber/wallet:staging

staging_deployment:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  dependencies: []
  tags:
    - staging
  script:
    - *staging_deploy_script
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/

test_deployment:
  variables:
    GIT_STRATEGY: none
    GIT_CHECKOUT: "false"
  stage: deploy
  only:
    - development_testing
  dependencies: []
  tags:
    - staging
  script:
    - *staging_deploy_script

production_build:
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  stage: build
  tags:
    - builder
  script: 
    - cp public/production.config.js public/config.js
    - docker build -t jimber/wallet:$CI_COMMIT_TAG .
    - docker push jimber/wallet:$CI_COMMIT_TAG

production_deploy:
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  rules:
    - when: manual
  stage: deploy
  tags:
    - production
  script: 
    - docker pull jimber/wallet:$CI_COMMIT_TAG
    - docker rm -f wallet
    - docker run -d -it --name=wallet --network=3proxynet jimber/wallet:$CI_COMMIT_TAG